wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.14
    cli_version: 0.24.0
    framework: huggingface
    huggingface_version: 4.57.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1769072044
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      3:
      - 4
      - 13
      - 16
      - 42
      4: 3.11.14
      5: 0.24.0
      6: 4.57.3
      13: linux-x86_64
    e:
      2pbgb5l6dai28naqn9vm377hbbn0yi2v:
        os: Linux-5.15.186.el8-x86_64-with-glibc2.39
        python: CPython 3.11.14
        started_at: '2026-01-22T08:54:03.803024Z'
        args:
        - /work/ViTRA/ViTRA/multirun/2026-01-22/09-53-50/.submitit/%j
        program: -m submitit.core._submit
        git:
          remote_url: https://github.com/Juxh01/ViTRA.git
          commit: c05d3bd6e2e2ef18be2ad7dafccc83dfd7d20008
        root: /work/ViTRA/ViTRA/multirun/2026-01-22/09-53-50/0
        host: j-5528846-job-0
        executable: /work/ViTRA/ViTRA/.venv/bin/python
        cpu_count: 48
        cpu_count_logical: 96
        gpu_type: NVIDIA A100-PCIE-40GB
        gpu_count: 1
        disk:
          /:
            total: '3838880616448'
            used: '2494590799872'
        memory:
          total: '2164246085632'
        gpu_nvidia:
        - name: NVIDIA A100-PCIE-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-b395d0c6-bf76-1e0d-d520-77978088546c
        cuda_version: '12.8'
        slurm:
          submit_dir: /work/ViTRA/ViTRA
          topology_addr_pattern: node
          localid: '0'
          step_tasks_per_node: 1(x2)
          step_launcher_port: '34615'
          ntasks_per_node: '1'
          pmix_mapping_serv: (vector,(0,2,1))
          cluster_name: ucloud
          job_uid: '11042'
          submit_host: j-5528846-job-0
          step_id: '0'
          step_gpus: '0'
          job_user: ucloud
          open_mode: a
          prio_process: '0'
          job_cpus_per_node: 1(x2)
          jobid: '69'
          srun_comm_host: 10.42.22.19
          job_gid: '11042'
          procid: '0'
          gpus_on_node: '1'
          nnodes: '2'
          nodeid: '0'
          job_account: escience
          job_qos: normal
          distribution: cyclic
          job_start_time: '1769072031'
          nodelist: node[0-1]
          task_pid: '1078787'
          job_name: DeMo_GP_segmentation
          cpus_on_node: '1'
          step_num_tasks: '2'
          job_id: '69'
          srun_comm_port: '34615'
          ntasks: '2'
          job_num_nodes: '2'
          job_gpus: '0'
          job_partition: CLOUD
          pmixp_abort_agent_port: '44979'
          working_cluster: ucloud:j-5528846-job-0:6817:9984:101
          job_end_time: '1769074731'
          step_nodelist: node[0-1]
          gtids: '0'
          step_num_nodes: '2'
          launch_node_ipaddr: 10.42.22.19
          job_nodelist: node[0-1]
          conf: /etc/slurm/slurm.conf
          umask: '0022'
          nprocs: '2'
          stepid: '0'
          mpi_type: pmix_v4
          topology_addr: node0
          gpus_per_node: '1'
          tasks_per_node: 1(x2)
        writer_id: 2pbgb5l6dai28naqn9vm377hbbn0yi2v
name:
  desc: null
  value: SBDataset-google/vit-base-patch16-384-GP-DeMo
description:
  desc: null
  value: Semantic Segmentation on SBDataset using google/vit-base-patch16-384 model
seed:
  desc: null
  value: 10
general:
  desc: null
  value:
    seed: 10
    backbone_name: google/vit-base-patch16-384
    wandb_project: ViTRA
    experiment_name: SBDataset-google/vit-base-patch16-384-GP-DeMo
    log_offline: true
    task: segmentation
    data_dir: /work/ViTRA/ViTRA/data/VOCSB/
    dataset_name: SBDataset
    num_classes: 21
    log_model_wandb: false
    log_images_wandb: false
optimizer:
  desc: null
  value:
    lr: 1.0e-05
    lr_head: 0.0001
    lr_power: 0.9
    momentum: 0.9
    optimizer_str: sgd
    batch_size_per_device: 32
    warmup_epochs: 5
    epochs: 15
    replicate_every: 1
    skip_every: null
    shards: 1
    repl: deto-demo
    compression_topk: 32
    compression_chunk: 64
    compression_rate: 0.2
    compression_chunk_factor: 6
distributed:
  desc: null
  value:
    nproc_per_node: 1
    nnodes: 2
    node_rank: 0
    master_addr: 10.42.22.19
    master_port: 27501
    standalone: false
